name: 'my first container action'
description: 'test containeraction'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome kasi'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
