on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'viswanathan'
    - name: output the memory
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "job finished"
